const COACHES_STORAGE_KEY='academyCoaches';const PLAYERS_STORAGE_KEY='academyPlayers';const DEFAULT_COACHES=[{id:1,code:'COA-0001',fullName:'أحمد علي حكمي',jobTitle:'مدرب رئيسي',specialty:'التدريب الفني',category:'شباب',experienceYears:12,bio:'يقود البرنامج الفني لفئة الشباب ويركز على التنظيم التكتيكي وتطوير القرار داخل الملعب.'},{id:2,code:'COA-0002',fullName:'محمد سالم مجرشي',jobTitle:'مدرب لياقة',specialty:'اللياقة البدنية',category:'فريق أول',experienceYears:9,bio:'مسؤول عن الإعداد البدني ورفع الجاهزية وتحسين التحمل والسرعة.'},{id:3,code:'COA-0003',fullName:'عبدالله حسن عواجي',jobTitle:'مدرب حراس',specialty:'تدريب الحراس',category:'كل الفئات',experienceYears:7,bio:'يشرف على تدريب الحراس ويركز على التمركز وردة الفعل والبناء من الخلف.'}];
const DEFAULT_PLAYERS=[{id:1,fullName:'محمد القحطاني',position:'مهاجم',category:'شباب',goals:9,assists:4,avgRate:9.4,playerStatus:'نشط'},{id:2,fullName:'عبدالله حسن',position:'حارس مرمى',category:'براعم',goals:0,assists:0,avgRate:8.2,playerStatus:'نشط'},{id:3,fullName:'أحمد علي',position:'مهاجم',category:'ناشئين',goals:7,assists:2,avgRate:8.8,playerStatus:'نشط'},{id:4,fullName:'حسن حكمي',position:'جناح',category:'شباب',goals:6,assists:5,avgRate:8.9,playerStatus:'نشط'},{id:5,fullName:'محمد يحيى',position:'وسط',category:'فريق أول',goals:3,assists:6,avgRate:8.5,playerStatus:'نشط'}];
function readCoaches(){try{const raw=JSON.parse(localStorage.getItem(COACHES_STORAGE_KEY)||'[]');return Array.isArray(raw)&&raw.length?raw:DEFAULT_COACHES}catch(e){return DEFAULT_COACHES}}
function readPlayers(){try{const raw=JSON.parse(localStorage.getItem(PLAYERS_STORAGE_KEY)||'[]');return Array.isArray(raw)&&raw.length?raw:DEFAULT_PLAYERS}catch(e){return DEFAULT_PLAYERS}}
function escapeHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function getInitials(name){const text=String(name||'').trim();if(!text)return '👤';const parts=text.split(/\s+/).filter(Boolean);if(parts.length===1)return parts[0].slice(0,2);return (parts[0][0]||'')+(parts[1][0]||'')}
function normalizeCategory(v){return String(v||'').replace('فئة ','').trim() || '-'}function getGoals(p){return Number(p.goals||0)}function getAssists(p){return Number(p.assists||0)}
function getRating(p){const direct=Number(p.avgRate||p.rating||0);if(!isNaN(direct)&&direct>0)return direct;const vals=['pac','sho','pas','dri','def','phy'].map(k=>Number(p[k])).filter(v=>!isNaN(v)&&v>0);if(vals.length)return Math.round((vals.reduce((a,b)=>a+b,0)/vals.length)*10)/10;return 7.5}
function overallFromPlayer(p){const vals=['pac','sho','pas','dri','def','phy'].map(k=>Number(p[k])).filter(v=>!isNaN(v)&&v>0);if(vals.length)return Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);return Math.min(94, Math.max(72, Math.round(getRating(p)*10)))}
function getTopPlayer(players){return players.slice().sort((a,b)=>((getGoals(b)*3)+(getAssists(b)*2)+getRating(b))-((getGoals(a)*3)+(getAssists(a)*2)+getRating(a)))[0]}
function renderWeekStar(){const root=document.getElementById('weekStarRoot');if(!root) return;const players=readPlayers();const star=getTopPlayer(players);if(!star){root.innerHTML='<div class="card week-star"><div class="week-star-card"><div class="week-star-content"><div class="week-star-title">نجم الأسبوع</div><div class="week-star-name">لا يوجد لاعب</div></div></div></div>';return;}const avatar=star.image?`<img src="${escapeHtml(star.image)}" alt="${escapeHtml(star.fullName)}">`:`<span>${escapeHtml(getInitials(star.fullName))}</span>`;root.innerHTML=`<div class="card week-star"><div class="week-star-card"><div class="week-star-cover"><div class="week-star-top-badge">نجم الأسبوع</div><div class="week-star-ovr">${overallFromPlayer(star)}<small>التقييم</small></div><div class="week-star-photo">${avatar}</div></div><div class="week-star-content"><div class="week-star-title">اللاعب الأكثر تأثيرًا</div><div class="week-star-name">${escapeHtml(star.fullName||'-')}</div><div class="week-star-sub">${escapeHtml(star.position||'لاعب')} • ${escapeHtml(normalizeCategory(star.category))}</div><div class="week-star-tags"><div class="week-star-tag">${escapeHtml(star.playerStatus||star.status||'نشط')}</div><div class="week-star-tag">${escapeHtml(normalizeCategory(star.category))}</div><div class="week-star-tag">جاهز للتألق</div></div><div class="week-star-kpi"><div class="box"><div class="n">${getGoals(star)}</div><div class="t">أهداف</div></div><div class="box"><div class="n">${getAssists(star)}</div><div class="t">صناعة</div></div><div class="box"><div class="n">${getRating(star)}</div><div class="t">التقييم</div></div></div><a class="week-star-btn" href="al_masariha_players_page.html">عرض صفحة اللاعبين</a></div></div></div>`}
function renderFeaturedPlayers(){const grid=document.getElementById('homeFeaturedPlayers');if(!grid) return;const allPlayers=readPlayers().slice().sort((a,b)=>getRating(b)-getRating(a));let players=allPlayers.slice(0,4);if(players.length<4){const names=new Set(players.map(p=>String(p.fullName||'').trim()));DEFAULT_PLAYERS.forEach(p=>{if(players.length<4&&!names.has(String(p.fullName||'').trim())){players.push(p);names.add(String(p.fullName||'').trim())}})}if(!players.length){grid.innerHTML='<div class="empty-box" style="grid-column:1/-1">لا يوجد لاعبون مضافون بعد.</div>';return;}grid.innerHTML=players.map(p=>{const avatar=p.image?`<img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.fullName)}">`:'⚽';return `<a class="player-link" href="al_masariha_players_page.html"><article class="player"><div class="photo">${avatar}</div><div class="meta"><b>${escapeHtml(p.fullName||'-')}</b><span>${escapeHtml(p.position||'لاعب')}</span><small>${escapeHtml(normalizeCategory(p.category))}</small><div class="go">←</div></div></article></a>`}).join('')}
function renderHomeCoaches(){const coaches=readCoaches().slice(0,4);document.getElementById('heroCoachesCount').textContent=coaches.length;const grid=document.getElementById('homeCoachesGrid');if(!coaches.length){grid.innerHTML='<div class="empty-box" style="grid-column:1/-1">لا يوجد مدربون مضافون بعد.</div>';return;}grid.innerHTML=coaches.map(c=>`<article class="coach"><div class="photo">${c.image?`<img src="${escapeHtml(c.image)}" alt="${escapeHtml(c.fullName)}">`:escapeHtml(getInitials(c.fullName))}<div class="coach-badge">${escapeHtml(c.specialty||'مدرب')}</div></div><div class="meta"><b>${escapeHtml(c.fullName)}</b><span>${escapeHtml(c.jobTitle||'-')}</span><small>${escapeHtml(c.category||'-')} • ${escapeHtml(c.experienceYears||0)} سنوات خبرة</small><div class="coach-snippet">${escapeHtml((c.bio||'')).slice(0,100) || 'ملف تدريبي احترافي مضاف من لوحة التحكم.'}</div><a class="go" href="al_masariha_coaches_page.html">←</a></div></article>`).join('')}
renderWeekStar();renderFeaturedPlayers();renderHomeCoaches();
